version: "3.5"
services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
    - "$PWD/files:/app/files"
    restart: unless-stopped
    depends_on:
      - tari
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
