version: "3.5"
services:
  api:
    build:
      context: .
    env_file: .env
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - tari
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3
  tari:
    image: quay.io/krakaw/tari-docker:latest
    volumes:
      - "$PWD/data/tari:/root/.tari"
    stdin_open: true
    tty: true
